# Generated by Django 3.2.20 on 2023-10-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0004_imagewithtext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageWithText',
        ),
        migrations.AlterField(
            model_name='labeleddata',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
